// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"net/http"

	"github.com/entkit/entkit"
	"github.com/gin-gonic/gin"
)

// _entkitDefaultValue to provide default values from entc definition and also get ability to provide from caller
func _entkitDefaultValue(value string, defaultValue string) string {
	if value == "" {
		return defaultValue
	}
	return value
}

func EntkitAuthMiddleware(
	next http.Handler,
	keycloakHost string,
	keycloakRealm string,
	keycloakBackendClientID string,
	keycloakBackendClientSecret string,
) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		w.Header().Set("Access-Control-Allow-Origin", "*")
		w.Header().Set("Access-Control-Allow-Methods", "POST, GET")
		w.Header().Set("Access-Control-Allow-Headers", "Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization")
		var err error
		kc := entkit.NewBackendKeycloak(
			_entkitDefaultValue(keycloakHost, "http://localhost:8080"),
			_entkitDefaultValue(keycloakRealm, "entkit-demo-3"),
			_entkitDefaultValue(keycloakBackendClientID, "backend"),
			_entkitDefaultValue(keycloakBackendClientSecret, "test-secret"),
		)
		r, err = kc.MiddlewareReqHandlerFunc(w, r)
		if err == nil {
			next.ServeHTTP(w, r)
		}
	})
}

func EntkitAuthGinMiddleware(
	keycloakHost string,
	keycloakRealm string,
	keycloakBackendClientID string,
	keycloakBackendClientSecret string,
) gin.HandlerFunc {
	return func(c *gin.Context) {
		c.Header("Access-Control-Allow-Origin", "*")
		c.Header("Access-Control-Allow-Methods", "POST, GET")
		c.Header("Access-Control-Allow-Headers", "Accept, Content-Type, Content-Length, Accept-Encoding, X-CSRF-Token, Authorization")
		var err error
		kc := entkit.NewBackendKeycloak(
			"http://localhost:8080",
			"entkit-demo-3",
			"backend",
			"test-secret",
		)
		c.Request, err = kc.MiddlewareReqHandlerFunc(c.Writer, c.Request)
		if err == nil {
			c.Next()
		} else {
			c.Abort()
		}
	}
}

type DemoResource int

const (
	DemoCompanyResource DemoResource = iota
	DemoCountryResource
	DemoEmailResource
	DemoImageResource
	DemoLocationResource
	DemoPhoneResource
	DemoProductResource
	DemoVendorResource
	DemoWarehouseResource
	DemoWebsiteResource
)

func (e DemoResource) String() string {
	switch e {
	case DemoCompanyResource:
		return "DemoCompany"
	case DemoCountryResource:
		return "DemoCountry"
	case DemoEmailResource:
		return "DemoEmail"
	case DemoImageResource:
		return "DemoImage"
	case DemoLocationResource:
		return "DemoLocation"
	case DemoPhoneResource:
		return "DemoPhone"
	case DemoProductResource:
		return "DemoProduct"
	case DemoVendorResource:
		return "DemoVendor"
	case DemoWarehouseResource:
		return "DemoWarehouse"
	case DemoWebsiteResource:
		return "DemoWebsite"
	default:
		return "unknown"
	}
}

type DemoScope int

const (
	DemoReadScope DemoScope = iota
	DemoCreateScope
	DemoUpdateScope
	DemoDeleteScope
	DemoMyCustomActionButtonScope
)

func (e DemoScope) String() string {
	switch e {
	case DemoReadScope:
		return "DemoRead"
	case DemoCreateScope:
		return "DemoCreate"
	case DemoUpdateScope:
		return "DemoUpdate"
	case DemoDeleteScope:
		return "DemoDelete"
	case DemoMyCustomActionButtonScope:
		return "DemoMyCustomActionButton"
	default:
		return "unknown"
	}
}

func EntkitAuthorizeByResource(ctx context.Context, resource DemoResource, scope DemoScope) error {
	authContext, err := EntkitAuthContextFromRequestContext(ctx)
	if err != nil {
		return err
	}
	auth := false
	for _, p := range authContext.Permissions {
		if p.Resource == resource.String() {
			for _, _scope := range p.Scopes {
				if _scope == scope.String() {
					auth = true
					break
				}
			}
		}
	}
	if !auth {
		return errors.New("access restricted for " + resource.String() + " " + scope.String())
	}
	return nil
}

func EntkitAuthContextFromRequestContext(ctx context.Context) (*entkit.AuthContext, error) {
	val := ctx.Value(entkit.AuthContextKey)
	if val == nil {
		err := fmt.Errorf("could not retrieve AuthContext")
		return nil, err
	}

	raw, ok := val.(*entkit.AuthContext)
	if !ok {
		return nil, fmt.Errorf("could not convert AuthContext")
	}
	return raw, nil
}
