// Autogenerated by entkit
//
// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Company is the predicate function for company builders.
type Company func(*sql.Selector)

// Country is the predicate function for country builders.
type Country func(*sql.Selector)

// Email is the predicate function for email builders.
type Email func(*sql.Selector)

// Image is the predicate function for image builders.
type Image func(*sql.Selector)

// Location is the predicate function for location builders.
type Location func(*sql.Selector)

// Phone is the predicate function for phone builders.
type Phone func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Vendor is the predicate function for vendor builders.
type Vendor func(*sql.Selector)

// Warehouse is the predicate function for warehouse builders.
type Warehouse func(*sql.Selector)

// Website is the predicate function for website builders.
type Website func(*sql.Selector)
